[package]
name = "minimp3"
version = "0.1.0"
authors = ["germän gômez <germangb42@gmail.com>"]
description = "Rust bindings for the minimp3 library."
keywords = ["mp3", "audio", "decoder", "mpeg", "media"]
categories = ["multimedia", "multimedia::audio"]
license = "MIT"
repository = "https://github.com/germangb/minimp3-rs.git"

[workspace]

[dependencies]
minimp3-sys = { path = "minimp3-sys" }